discord:
  token: "${DISCORD_FLECTONE_BOT_TOKEN}"
  guild_id: 861147957365964810
  messages:
    no_permission: "‚ùå –ù–µ—Ç –ø—Ä–∞–≤"
    unknown_command: "‚ùå –ù–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –∫–æ–º–∞–Ω–¥–∞!"
    command_error: "‚ùå –ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞ –ø—Ä–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–∏ –∫–æ–º–∞–Ω–¥—ã!"
    ticket_close_no_permission: "‚ùå –¢–æ–ª—å–∫–æ —Å–æ–∑–¥–∞—Ç–µ–ª—å —Ç–∏–∫–µ—Ç–∞ –∏–ª–∏ –º–æ–¥–µ—Ä–∞—Ç–æ—Ä –º–æ–∂–µ—Ç –µ–≥–æ –∑–∞–∫—Ä—ã—Ç—å"
    ticket_closed: "‚úÖ –¢–∏–∫–µ—Ç –∑–∞–∫—Ä—ã—Ç"
    not_a_thread: "‚ùå –≠—Ç–æ –Ω–µ —Ç—Ä–µ–¥"
  presence:
    enable: true
    status: "ONLINE"
    activity:
      enable: true
      type: "PLAYING"
      name: "FlectoneBot –≤–∫–ª—é—á–µ–Ω"
      url: "https://flectone.net/pulse/"
  ticket:
    permission_role: 959813465025949747
    close_tag_id: 1285574391144644630
    modals:
      russian_idea:
        name: "–ü—Ä–µ–¥–ª–æ–∂–µ–Ω–∏–µ"
        embed:
          color: "#2ecc71"
          title: "<name>"
          author:
            name: "–ü—Ä–µ–¥–ª–æ–∂–µ–Ω–∏–µ –æ—Ç <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞"
              value: "``<platform>``"
              inline: false
          timestamp: true
        create_message:
          message: "–ü—Ä–µ–¥–ª–æ–∂–µ–Ω–∏–µ —Å–æ–∑–¥–∞–Ω–æ, –ø–µ—Ä–µ–π–¥–∏ –≤ <thread>"
        buttons:
          - id: "close_button"
            name: "üîí –ó–∞–∫—Ä—ã—Ç—å"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852198359466034
        text_inputs:
          - id: "name"
            name: "–ù–∞–∑–≤–∞–Ω–∏–µ"
            placeholder: "–î–æ–±–∞–≤–∏—Ç—å –Ω–æ–≤—ã–µ —Å–æ–æ–±—â–µ–Ω–∏—è..."
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "–û–ø–∏—Å–∞–Ω–∏–µ"
            placeholder: "–Ø —Ö–æ—á—É, —á—Ç–æ–±—ã –¥–æ–±–∞–≤–∏–ª–∏..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞, –≤–µ—Ä—Å–∏—è FlectonePulse"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
      russian_bug:
        name: "–ë–∞–≥"
        embed:
          color: "#5865f2"
          title: "<name>"
          author:
            name: "–ë–∞–≥ –æ—Ç <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞"
              value: "``<platform>``"
              inline: false
            - name: "–ü–ª–∞–≥–∏–Ω—ã/–ú–æ–¥—ã"
              value: "``<plugins>``"
              inline: false
          timestamp: true
        create_message:
          message: "–ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –±–∞–≥–µ —Å–æ–∑–¥–∞–Ω–∞, –ø–µ—Ä–µ–π–¥–∏ –≤ <thread>"
        buttons:
          - id: "close_button"
            name: "üîí –ó–∞–∫—Ä—ã—Ç—å"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852374931279974
        text_inputs:
          - id: "name"
            name: "–ù–∞–∑–≤–∞–Ω–∏–µ"
            placeholder: "–ù–µ –∑–∞–ø—É—Å–∫–∞–µ—Ç—Å—è..."
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "–û–ø–∏—Å–∞–Ω–∏–µ"
            placeholder: "–Ø —Ö–æ—á—É –∑–∞–ø—É—Å—Ç–∏—Ç—å, –Ω–æ –Ω–µ –∑–∞–ø—É—Å–∫–∞–µ—Ç—Å—è..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞, –≤–µ—Ä—Å–∏—è FlectonePulse"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
          - id: "plugins"
            name: "–°–ø–∏—Å–æ–∫ –ø–ª–∞–≥–∏–Ω–æ–≤ –∏–ª–∏ –º–æ–¥–æ–≤ –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ"
            placeholder: "FlectonePulse, Vault, LuckPerms..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
      russian_question:
        name: "–í–æ–ø—Ä–æ—Å"
        embed:
          color: "#7f8c8d"
          title: "<name>"
          author:
            name: "–í–æ–ø—Ä–æ—Å –æ—Ç <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞"
              value: "``<platform>``"
              inline: false
          timestamp: true
        create_message:
          message: "–í–æ–ø—Ä–æ—Å —Å–æ–∑–¥–∞–Ω, –ø–µ—Ä–µ–π–¥–∏ –≤ <thread>"
        buttons:
          - id: "close_button"
            name: "üîí –ó–∞–∫—Ä—ã—Ç—å"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852440047714324
        text_inputs:
          - id: "name"
            name: "–ù–∞–∑–≤–∞–Ω–∏–µ"
            placeholder: "–ö–∞–∫ –≤–∫–ª—é—á–∏—Ç—å –∏–º–µ–Ω–∞ –Ω–∞–¥ –∏–≥—Ä–æ–∫–∞–º–∏?"
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "–û–ø–∏—Å–∞–Ω–∏–µ"
            placeholder: "–Ø —Ö–æ—á—É —á—Ç–æ–±—ã –Ω–∞–¥ –∏–≥—Ä–æ–∫–∞–º–∏ –±—ã–ª–∏ –≤–∏–¥–Ω—ã –∏—Ö –∏–º–µ–Ω–∞..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞, –≤–µ—Ä—Å–∏—è FlectonePulse"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
      english_idea:
        name: "Suggestion"
        embed:
          color: "#2ecc71"
          title: "<name>"
          author:
            name: "Suggestion from <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "Platform"
              value: "``<platform>``"
              inline: false
          timestamp: true
        create_message:
          message: "Suggestion created, go to <thread>"
        buttons:
          - id: "close_button"
            name: "üîí Close"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852198359466034
        text_inputs:
          - id: "name"
            name: "Title"
            placeholder: "Add new messages..."
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "Description"
            placeholder: "I want to add..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "Platform, FlectonePulse version"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
      english_bug:
        name: "Bug"
        embed:
          color: "#5865f2"
          title: "<name>"
          author:
            name: "Bug from <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "Platform"
              value: "``<platform>``"
              inline: false
            - name: "Plugins/Mods"
              value: "``<plugins>``"
              inline: false
          timestamp: true
        create_message:
          message: "Bug report created, go to <thread>"
        buttons:
          - id: "close_button"
            name: "üîí Close"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852374931279974
        text_inputs:
          - id: "name"
            name: "Title"
            placeholder: "Doesn't start..."
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "Description"
            placeholder: "I want to start it, but it doesn't start..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "Platform, FlectonePulse version"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
          - id: "plugins"
            name: "List of plugins or mods on the server"
            placeholder: "FlectonePulse, Vault, LuckPerms..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
      english_question:
        name: "Question"
        embed:
          color: "#7f8c8d"
          title: "<name>"
          author:
            name: "Question from <username>"
            icon_url: "<skin>"
          description: "<description>"
          fields:
            - name: "Platform"
              value: "``<platform>``"
              inline: false
          timestamp: true
        create_message:
          message: "Question created, go to <thread>"
        buttons:
          - id: "close_button"
            name: "üîí Close"
            style: "SECONDARY"
        forum_id: 1271850075064369152
        tag_id: 1271852440047714324
        text_inputs:
          - id: "name"
            name: "Title"
            placeholder: "How to enable player names above heads?"
            style: "SHORT"
            max_length: 100
            required: true
          - id: "description"
            name: "Description"
            placeholder: "I want to see player names above their heads..."
            style: "PARAGRAPH"
            max_length: 1000
            required: true
          - id: "platform"
            name: "Platform, FlectonePulse version"
            placeholder: "Paper 1.21.11 (Velocity). FlectonePulse 1.7.3"
            style: "SHORT"
            max_length: 100
            required: true
  commands:
    - name: "–ø–∏–Ω–≥"
      description: "–ü—Ä–æ–≤–µ—Ä–∏—Ç—å –∑–∞–¥–µ—Ä–∂–∫—É –±–æ—Ç–∞"
      message: "–ü–æ–Ω–≥ üèì"
      private_reply: false
      options: []
    - name: "–∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è"
      description: "–ì–∞–π–¥—ã –Ω–∞ –≤—Å—é –∂–∏–∑–Ω—å"
      message: "https://www.youtube.com/watch?v=WHPxQxY33Is"
      private_reply: false
      options:
        - type: "SUB_COMMAND"
          name: "—Ñ–æ—Ä—É–º"
          description: "–ì–∞–π–¥ –Ω–∞ —Ñ–æ—Ä—É–º"
          message: "–ù–µ –∑–Ω–∞–µ—à—å –∫–∞–∫ –Ω–∞–ø–∏—Å–∞—Ç—å –∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Ñ–æ—Ä—É–º https://discord.com/channels/861147957365964810/1271850075064369152? \n–ü–æ—Å–º–æ—Ç—Ä–∏ —ç—Ç–æ—Ç –≥–∞–π–¥ https://www.youtube.com/watch?v=WHPxQxY33Is"
        - type: "SUB_COMMAND"
          name: "—Ñ–ª–µ–∫—Ç–æ–Ω–ø—É–ª—å—Å"
          description: "–î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –¥–ª—è FlectonePulse"
          message: "–î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –¥–ª—è FlectonePulse https://flectone.net/pulse/docs/"
        - type: "SUB_COMMAND"
          name: "—é—Ç—É–±"
          description: "–Æ—Ç—É–± –∫–∞–Ω–∞–ª –§–∞—Å—ç—Ä–∞"
          message: "–Æ—Ç—É–± –∫–∞–Ω–∞–ª –§–∞—Å—ç—Ä–∞ https://www.youtube.com/@thefaser/videos"
        - type: "SUB_COMMAND"
          name: "–±—É—Å—Ç–∏"
          description: "–ü–æ–¥–¥–µ—Ä–∂–∞—Ç—å –§–∞—Å—ç—Ä–∞ –∏ –µ–≥–æ –ø—Ä–æ–µ–∫—Ç–∞"
          message: "–ü–æ–¥–¥–µ—Ä–∂–∞—Ç—å –§–∞—Å—ç—Ä–∞ –∏ –µ–≥–æ –ø—Ä–æ–µ–∫—Ç—ã –º–æ–∂–Ω–æ —Ç—É—Ç https://boosty.to/thefaser, —Å–ø–∞—Å–∏–±–æ :heart:"
    - name: "–ø–∞—Å—Ç–∞"
      description: "–°–ª—É—á–∞–π–Ω—ã–µ –ø–∞—Å—Ç—ã –∏–∑ –∏–Ω—Ç–µ—Ä–Ω–µ—Ç–∞"
      message: "https://www.youtube.com/watch?v=WHPxQxY33Is"
      private_reply: false
      options:
        - type: "SUB_COMMAND"
          name: "–æ–∫–∞–∫"
          description: "–æ–∫–∞–∫"
          message: " ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚£æ‚°á‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢ê‚£∑‚°Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚£æ‚£ø‚†Ö‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢ø‚£∑‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Ä‚¢∞‚°ø‚†É‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†ò‚£ø‚°Ü‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Ä‚£æ‚†Å‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†ò‚£á‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Ä‚°á‚†Ä‚°§‚£∂‚°Ñ‚†Ä‚†Ä‚†Ä‚¢†‚£∂‚¢∂‚°Ñ‚¢π‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚¢∏‚†Ä‚†Ä‚†∑‚£§‚†ø‚†Ä‚†Ä‚†Ä‚†π‚£§‚†º‚†É‚†à‚†Ä‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†à‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚£Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚°á‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚°Ü‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†â‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚°á‚†Ä‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Å‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢á‚†Ä‚†Ä‚†Ä\n ‚†Ä‚†Ä‚£§‚£∂‚°Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚°ò‚†à‚†ô‚¢¶‚°Ä\n ‚¢†‚£æ‚£ø‚†á‚£∑‚°Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†â\n ‚£æ‚£º‚£ø‚†É‚¢∏‚£á‚†Ä‚†Ä‚£¥‚†∂‚£§‚¢†‚°Ü‚£†‚°ñ‚¢†‚†∂‚¢¶‚°Ä‚£¥‚¢Ä‚°¥\n ‚£ø‚°ü‚¢∏‚°Ü‚†ò‚°ü‚†Ä‚†∏‚£ß‚£Ä‚£ø‚¢∏‚°ü‚¢ø‚°Ñ‚¢¥‚£ã‚£π‚°á‚£ø‚†ª‚£ß"
        - type: "SUB_COMMAND"
          name: "–∫–∞–±–∞–Ω"
          description: "–∫–∞–±–∞–Ω"
          message: "–ú–£–ñ–ò–ö–ò –Ø –° –°–´–ù–ò–®–ö–û–ô –ë–ï–ì–£ –ù–ï –®–ú–ê–õ–Ø–ô–¢–ï –•–†–ò–°–¢–ê –†–ê–î–ò‚†Ä\n ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚£Ä‚£Ä‚£Ä‚£Ä‚£Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä \n ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚£∂‚£æ‚£∑‚£∂‚£æ‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£∂‚£¶‚£§‚£Ä‚°Ä‚¢Ä‚°§‚†í‚£¶‚†Ä \n ‚†Ä‚†Ä‚†Ä‚†Ä‚£†‚£æ‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚†Ä‚†Ä‚†ò‚†Ä \n ‚††‚£¥‚°æ‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚°Ä‚†Ä‚†Ä‚†Ä \n ‚†Ä‚†â‚¢≠‚£∂‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚°ü‚¢â‚£â‚£Ä‚£†‚£§‚£Ñ‚£Ä‚°à‚†â‚¢É‚†Ä‚†Ä‚†Ä \n ‚†Ä‚†Ä‚†Ä‚†â‚†ô‚†â‚†ã‚†õ‚†õ‚£õ‚£ø‚£ø‚£ø‚£ø‚†è‚£Å‚£§‚£æ‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚£ø‚°Ä‚†Å‚°Ä‚†Ä \n ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚¢Ä‚£º‚†õ‚†â‚†π‚¢ø‚£≠‚†Ä‚†Ä‚†ì‚†õ‚¢õ‚£ª‚£ø‚°ü‚†ø‚†ü‚£ø‚¢ø‚£ß‚°Ä‚£ß‚†Ä \n ‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†õ‚†Å‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†Ä‚†ä‚†â‚†â‚†Ä‚†Ä‚†ä‚†Ä‚†Ä‚†Ä‚†á‚¢π‚†Ü\n"
    - name: "ticket"
      description: "–°–æ–∑–¥–∞—Ç—å —Ç–∏–∫–µ—Ç"
      permission_role: 959813465025949747
      private_reply: false
      options:
        - type: "SUB_COMMAND"
          name: "russian"
          description: "–¢–∏–∫–µ—Ç –¥–ª—è —Ñ–æ—Ä—É–º–∞ FlectonePulse"
          embed:
            color: "#4287f5"
            title: "–¢–∏–∫–µ—Ç –¥–ª—è —Ñ–æ—Ä—É–º–∞ FlectonePulse"
            description: "–ï—Å–ª–∏ –≤–æ–∑–Ω–∏–∫–ª–∞ –æ—à–∏–±–∫–∞, –µ—Å—Ç—å –∏–¥–µ—è –∏–ª–∏ –ø–æ—è–≤–∏–ª—Å—è –≤–æ–ø—Ä–æ—Å, —Ç–æ –Ω–∞–∂–º–∏—Ç–µ –Ω–∞ –æ–¥–Ω—É –∏–∑ –∫–Ω–æ–ø–æ–∫ –Ω–∏–∂–µ, —á—Ç–æ–±—ã —Å–æ–∑–¥–∞—Ç—å —Ç–∏–∫–µ—Ç"
          buttons:
            - id: "russian_idea"
              name: "üí° –ü—Ä–µ–¥–ª–æ–∂–µ–Ω–∏–µ"
              style: "SUCCESS"
            - id: "russian_bug"
              name: "üêõ –ë–∞–≥"
              style: "PRIMARY"
            - id: "russian_question"
              name: "ü§î –í–æ–ø—Ä–æ—Å"
              style: "SECONDARY"
        - type: "SUB_COMMAND"
          name: "english"
          description: "Ticket for FlectonePulse forum"
          embed:
            color: "#4287f5"
            title: "Ticket for FlectonePulse forum"
            description: "If you have an error, suggestion, or question, click one of buttons below to create a ticket"
          buttons:
            - id: "english_idea"
              name: "üí° Suggestion"
              style: "SUCCESS"
            - id: "english_bug"
              name: "üêõ Bug"
              style: "PRIMARY"
            - id: "english_question"
              name: "ü§î Question"
              style: "SECONDARY"
telegram:
  token: "${TELEGRAM_FLECTONE_BOT_TOKEN}"